### PR TITLE
Update handbrake-full, handbrake-dev, and handbrake-git

### PR DESCRIPTION
**Pull request by HurricanePootis**
Handbrake downloads versions of dependencies through its make system. The PKGBUILDs also downloads these archives. However, since the PKGBUILD has not been updated in the versions of the archives, there is unnecessary downloading of archives:
```
Before patch:
.rw-r--r-- 4.6M hurricane 26 Jul 15:21 AMF-1.4.30-slim.tar.gz
.rw-r--r-- 1.2M hurricane 26 Jul 15:21 AMF-1.4.33.tar.gz
.rw-r--r-- 1.0M hurricane 26 Jul 15:21 dav1d-1.3.0.tar.bz2
.rw-r--r-- 1.1M hurricane 26 Jul 15:21 dav1d-1.4.3.tar.bz2
.rw-r--r-- 2.5M hurricane 26 Jul 15:21 fdk-aac-2.0.2.tar.gz
.rw-r--r-- 2.5M hurricane 26 Jul 15:21 fdk-aac-2.0.3.tar.gz
.rw-r--r--  13M hurricane 26 Jul 15:21 ffmpeg-6.1.tar.bz2
.rw-r--r--  13M hurricane 26 Jul 15:21 ffmpeg-7.0.1.tar.bz2
.rw-r--r-- 756k hurricane 26 Jul 15:21 libbluray-1.3.4.tar.bz2
.rw-r--r-- 455k hurricane 26 Jul 15:21 libdovi-3.2.0.tar.gz
.rw-r--r-- 368k hurricane 26 Jul 15:21 libdvdnav-6.1.1.tar.bz2
.rw-r--r-- 395k hurricane 26 Jul 15:21 libdvdread-6.1.3.tar.bz2
.rw-r--r--  12M hurricane 26 Jul 15:21 libvpl-2.10.1.tar.gz
.rw-r--r-- 2.7M hurricane 26 Jul 15:21 libvpx-1.7.0.tar.gz
.rw-r--r-- 151k hurricane 26 Jul 15:21 mfx_dispatch-1.35.tar.gz
.rw-r--r--  77k hurricane 26 Jul 15:21 nv-codec-headers-12.1.14.0.tar.gz
.rw-r--r-- 6.3M hurricane 26 Jul 15:21 oneVPL-2023.3.1.tar.gz
.rw-r--r--  10M hurricane 26 Jul 15:21 SVT-AV1-v1.7.0.tar.gz
.rw-r--r--  13M hurricane 26 Jul 15:21 SVT-AV1-v2.1.0.tar.gz
.rw-r--r-- 1.6M hurricane 26 Jul 15:21 x265-snapshot-20230403-12776.tar.gz
.rw-r--r-- 1.7M hurricane 26 Jul 15:21 x265_3.6.tar.gz
.rw-r--r-- 327k hurricane 26 Jul 15:21 zimg-3.0.5.tar.gz



After patch
.rw-r--r-- 1.2M hurricane 26 Jul 15:23 AMF-1.4.33.tar.gz
.rw-r--r-- 1.1M hurricane 26 Jul 15:23 dav1d-1.4.3.tar.bz2
.rw-r--r-- 2.5M hurricane 26 Jul 15:23 fdk-aac-2.0.3.tar.gz
.rw-r--r--  13M hurricane 26 Jul 15:23 ffmpeg-7.0.1.tar.bz2
.rw-r--r-- 756k hurricane 26 Jul 15:23 libbluray-1.3.4.tar.bz2
.rw-r--r-- 368k hurricane 26 Jul 15:23 libdvdnav-6.1.1.tar.bz2
.rw-r--r-- 395k hurricane 26 Jul 15:23 libdvdread-6.1.3.tar.bz2
.rw-r--r--  12M hurricane 26 Jul 15:23 libvpl-2.10.1.tar.gz
.rw-r--r--  77k hurricane 26 Jul 15:23 nv-codec-headers-12.1.14.0.tar.gz
.rw-r--r--  13M hurricane 26 Jul 15:23 SVT-AV1-v2.1.0.tar.gz
.rw-r--r-- 1.7M hurricane 26 Jul 15:23 x265_3.6.tar.gz
.rw-r--r-- 327k hurricane 26 Jul 15:23 zimg-3.0.5.tar.gz
```

And, especially for git packages where upstream can change the version of the files downloaded without a stable point release, I believe it'd be best to just let handbrake itself handle downloading these files, as upstream [handbrake does here](https://gitlab.archlinux.org/archlinux/packaging/packages/handbrake/-/blob/main/PKGBUILD?ref_type=heads).

Some additional changes are as follows:
### handbrake-full
1. Change license to be spdx compliant
2. Added `cuda` and `amf-amdgpu-pro` to optional deps
3. Enable nvdec
### handbrake-dev
1. Change license to be spdx compliant
2. Added 'amf-amdgpu-pro` to optional deps
3. Enable nvdec
### handbrake-git
1. Change license to be spdx compliant
2. Added 'amf-amdgpu-pro' to optional deps

### Note
I am sorry about my behavior on the AUR, it was unprofessional and unbecoming of me. I should've have known better, and for the future, I shall be proper and submit pull request to this repo. Thank you for your hard work in maintaing these packages.

### CODE REVIEW

**Comment by FabioLolix** [comment]
Hello @HurricanePootis 

When you made this PR I wasn't sold on removing the source archives yet for the moment are blacklisted in a new commit (you have to rebase sorry) since can't take care well of that anyway and worked on another thing

No need to apologize we're fine

**Comment by HurricanePootis** [comment]
@FabioLolix I have rebased the pull request

**Comment by FabioLolix** [comment]
btw please test the builds with devtools, enabling `nvdec` require `clang` (llvm don't seem needed from last test) at build time

```
evc_nvenc --enable-encoder=av1_nvenc --enable-hwaccels --enable-nvdec --enable-cuda-llvm --enable-cuda --enable-filter=colorspace_cuda --enable-filter=scale_cuda
ERROR: cuda_llvm requested but not found
```

**Comment by HurricanePootis** [comment]
> btw please test the builds with devtools, enabling `nvdec` require `clang` (llvm don't seem needed from last test) at build time
> 
> ```
> evc_nvenc --enable-encoder=av1_nvenc --enable-hwaccels --enable-nvdec --enable-cuda-llvm --enable-cuda --enable-filter=colorspace_cuda --enable-filter=scale_cuda
> ERROR: cuda_llvm requested but not found
> ```

Yes, I will in the future.

**Pull request merged**
